[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "php83Extensions.zip", "zip", "unzip"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-scripts --no-interaction --ignore-platform-req=ext-zip"]